# .github/workflows/build-docker-image.yml
name: build-binary-package

on: 
  release:
    types: prereleased

jobs:
  build-binary-package:
    name: Build and upload binary package
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.20.1
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build the binaries
      run: make release
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: crowdsec-custom-bouncer.tgz application/x-gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
