name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: "golangci-lint + codeql"
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go, python

    - name: Build
      run: |
        make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
          version: v2.5
          args: --issues-exit-code=1 --timeout 10m
          only-new-issues: false

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
